# Generated by Django 5.0.6 on 2024-06-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
