# Generated by Django 4.2 on 2024-07-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_communitypost_dislikes_communitypost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='price',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='timeline',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='role',
            field=models.CharField(max_length=100, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='sector',
            field=models.CharField(max_length=100, null=True, verbose_name='sector'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='sub_sector',
            field=models.CharField(max_length=100, null=True, verbose_name='sub_sector'),
        ),
    ]
