# Generated by Django 5.0.7 on 2024-07-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_remove_communitypost_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='role',
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='description',
            field=models.TextField(default='default_description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='sector',
            field=models.CharField(default='default_sector', max_length=100),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='sub_sector',
            field=models.CharField(default='default_sub_sector', max_length=100),
        ),
    ]
