# Generated by Django 5.0.6 on 2024-06-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_review_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
