# Generated by Django 4.2 on 2024-08-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default='slug', max_length=200),
        ),
    ]
